# manifest
[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

#domain calc
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "-- TARGET: add your own CardAreas for joker evaluation"
position = 'after'
match_indent = true
payload = '''
table.insert(t, G.domain)
'''