[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

#modular system UI
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
self.unique_val = 1-self.ID/1603301
self.edition = nil
'''
position = "after"
payload = '''
self.slots = center.slots or 1
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
return generate_card_ui(self.config.center, nil, loc_vars, card_type, badges, hide_desc, main_start, main_end, self)
'''
position = "at"
payload = '''
local full_UI_table = generate_card_ui(self.config.center, nil, loc_vars, card_type, badges, hide_desc, main_start, main_end, self)
if self and self.slots ~= 1 then
  full_UI_table.multi_box = full_UI_table.multi_box or {}
  local mb = #full_UI_table.multi_box
  full_UI_table.main.main_box_flag = true
  local k = G.localization.descriptions['Other']['jjok_slots']
  for i, box in ipairs(k.text_parsed) do
    for j, line in ipairs(box) do
      local o = SMODS.localize_box(line, {scale = 1, vars = {tostring(self.slots)}})
      full_UI_table.multi_box[mb + 1] = full_UI_table.multi_box[mb + 1] or {}
      full_UI_table.multi_box[mb + 1][#full_UI_table.multi_box[mb + 1] + 1] = o
    end
  end
end
return full_UI_table
'''
match_indent = true

#random slots (polled by rarity, edition and stickers)
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''
card:set_edition(edition)
        check_for_unlock({type = 'have_edition'})
        end'''
position = "at"
payload = '''
if Jjok.config.slotsystem then
    local slots, pool = card.slots or 1, 0

    --Rarities n stuff
    if center.rarity == 2 then
      pool = pool + 0.2
    elseif center.rarity == 3 then
      pool = pool + 0.45
    elseif center.rarity == 4 then
      pool = pool + 0.6
    elseif center.rarity == 'jjok_special' then
      pool = pool + 0.75
    end

    --editions smile :)
    if card.edition then
      if card.edition.key == 'e_foil' then
        pool = pool + 0.1
      elseif card.edition.key == 'e_holo' then
        pool = pool + 0.2
      elseif card.edition.key == 'e_polychrome' then
        pool = pool + 0.3
      end
    end

    --stinkers
    if card.ability then
      local st = card.ability
      if st.rental then
        pool = pool - 0.2
      elseif st.eternal then
        pool = pool - 0.3
      elseif st.perishable then
        pool = pool - 0.15
      end
    end
    
    if pool > 0 then
      if pseudorandom('jjok_slots', 1, 100) <= (pool * 100) then
        card.slots = 2
      end
    end
    end
end
'''
match_indent = true